import type { Metadata } from "next";
import { Geist, Quicksand } from "next/font/google";
import "./globals.css";
import Provider from "@/components/HOC/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  weight: ["500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-quicksand",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="color-scheme: light">
      <body className={`${quicksand.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
